[package]
name = "artifactarium-proc-macro"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.79"
tracing = "0.1.40"
